version: "3.7"

services:
  sdc_overview:
    image: ganzfriend/sdc_overview:latest
    ports:
      - "3001:3001"
    depends_on:
      - db
    container_name: sdc_overview
    environment:
      - PORT=3001

  db:
    image: postgres
    restart: always
    volumes:
      - sdc:/data/db
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_PASSWORD: password

volumes:
  sdc:
